name: Alpha-Deploy

on: 
  push:
    branches: [alpha-test]


jobs:
  last-minute-test:
    permissions:
      contents: read
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: set up python  3.14
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with: 
          python-version: 3.14
      - run: pip install . montepy[develop]
      - run: python -m pytest
      
  build-packages:
    name: Build, sign, and release packages on github
    environment:
      name: build-pypi
    runs-on: ubuntu-latest
    needs: [last-minute-test]
    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false
      - name: set up python  3.14
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with: 
          python-version: 3.14
      - run: pip install . montepy[build]
      - name: Get Version
        id: get_version
        run: echo "version=`python -m setuptools_scm`" >> $GITHUB_OUTPUT
      - name: Verify that this is a non-dev alpha release
        run: .github/scripts/check_version.py --alpha 
      - run: python -m build .
      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@5b79a39c381910c090341a2c9b0bf022c8b387e1
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl
      - name: Create a GitHub release
        run: |
            gh release create "v${{ steps.get_version.outputs.version }}" \
            --title="Release ${{ steps.get_version.outputs.version }}" \
            --generate-notes -d
      - run: >-
          gh release upload
          'v${{ steps.get_version.outputs.version }}' dist/**
          --repo '${{ github.repository }}'
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with: 
           name: build
           path: |
               dist/*.tar.gz 
               dist/*.whl


  deploy-test-pypi: 
    environment:
      name: test-pypi
      url: https://test.pypi.org/p/montepy  # Replace <package-name> with your PyPI project name
    needs: [build-packages]
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: build
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247
        with:
          repository-url: https://test.pypi.org/legacy/

  deploy-pypi: 
    environment:
      name: pypi
      url: https://pypi.org/p/montepy  # Replace <package-name> with your PyPI project name
    needs: [deploy-test-pypi, build-packages]
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: build
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247

