name: add RTD links
on:
  pull_request_target:
    types: [opened, reopened, edited]
jobs:
  add_rtd_link:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@31a30360a2d7530806bff6855aa209167f06a89c
        with:
          project-slug: "montepy"
