name: add RTD links
on:
  pull_request_target:
    types: [opened, reopened, edited]
jobs:
  add_rtd_link:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@fa6846867b4616e65886b37ae564cb695e8dc570
        with:
          project-slug: "montepy"
